services:
  backend:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_DIALECT=${DB_DIALECT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - APP_PORT=${APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  db:
    image: mysql:8.0  
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./data/01-init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ./data/02-seed-users.sql:/docker-entrypoint-initdb.d/02-seed-users.sql
    ports:
      - "3307:3306/tcp"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    restart: unless-stopped

volumes:
  db_data:

